language: python
python: "2.7"

dist: trusty

branches:
  only:
    - /.*/

sudo: false

addons:
  apt:
    packages:
      - libwww-perl
      - libcss-dom-perl
  chrome: stable

cache:
  directories:
    - node_modules # NPM packages

before_install:
  - nvm install lts/*

install:
 - export RESPEC_RELEASE="v24.32.1"
 - make travissetup

script:
 - make check

env:
  global:
    - URL="https://w3c.github.io/webrtc-pc/W3CTRMANIFEST"
    - DECISION="https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html"
    - secure: "CulTjFgWSB/QDuJmmdSdy7sDYhK5s6EvL69ce5vk52DROpvDMgTYvQRzLL1cR+6E/+fA5U9T/cJkP9UGI75NGsgydM+t6aQ/yTyI4ttp4gyHN80aKeOqlHC7zrbFtPWsvXoIxW2pB9pP9RaFCkuz2Ul83ps/f38RJ/NsGEkNUOQ="

after_success:
  - test $TRAVIS_BRANCH = "gh-pages" -a $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
