name: Validate Spec

on: pull_request
jobs:
  validate-spec:
    name: Validate specification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install respec respec-validator
    - run: npx respec-validator --no-links webrtc.html
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
